version: '2'
services:
    pg:
        image: itsalgeria/postgresql:stable
        restart: always
        volumes:
          - ./pg_data:/var/lib/postgresql:rw
          - ./pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf:rw

    pgbouncer:
        image: itsalgeria/pgbouncer
        build: .
        environment:
          PG_PORT_5432_TCP_ADDR: postgres
          PG_PORT_5432_TCP_PORT: 5432
          PG_ENV_POSTGRESQL_USER: pg
          PG_ENV_POSTGRESQL_PASS: suchsecuremanypassword
        links:
          - pg
